name: upass
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - pytorch
    - anaconda
    - fastai
dependencies:
    - python>3.6
    - numpy
    - matplotlib
    - seaborn
    - pandas
    # DL related
    - pytorch
    - torchvision
    - libjpeg-turbo
    - mkl
    - scikit-learn
    - fastai
     # for Jupyter
    - jupyter
    - rise
    - jupyter_contrib_nbextensions 
    # for VS code
    - pylint
    - autopep8
    - pip
    - pip:
        - torchtext
